name: CI Probe GD Fiscal
on:
  push:
    branches: [ci-probe-gd-fiscal]
jobs:
  probe:
    runs-on: windows-2022
    steps:
      - run: |
          echo PUBLIC_WINDOWS_RUNNER_OK
          go version
